services:
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  cache-dashboard:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  timescale:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db

volumes:
  cache: